name: PHPUnit

on:
    pull_request:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    phpunit:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    - php_version: "8.2"
                      dependency_version: "--prefer-lowest"

                    - php_version: "8.3"
                      dependency_version: "--prefer-lowest"

                    - php_version: "8.4"
                      dependency_version: "--prefer-lowest"

                    - php_version: "8.5"
                      dependency_version: "--prefer-lowest"

                    - php_version: "8.2"
                      dependency_version: ""

                    - php_version: "8.3"
                      dependency_version: ""

                    - php_version: "8.4"
                      dependency_version: ""

                    - php_version: "8.5"
                      dependency_version: ""

        name: PHPUnit with PHP ${{ matrix.php_version }} ${{ matrix.dependency_version }}

        env:
            PHP_EXTENSIONS: xdebug,gmp,bcmath
            PHP_EXTENSIONS_CACHE_KEY: cache-v1

        steps:
            - uses: actions/checkout@v4

            - name: Setup Cache environment
              id: extcache
              uses: shivammathur/cache-extensions@v1
              with:
                  php-version: ${{ matrix.php_version }}
                  extensions: ${{ env.PHP_EXTENSIONS }}
                  key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}

            - name: Cache PHP extensions
              uses: actions/cache@v4
              with:
                  path: ${{ steps.extcache.outputs.dir }}
                  key: ${{ steps.extcache.outputs.key }}
                  restore-keys: ${{ steps.extcache.outputs.key }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}
                  extensions: ${{ env.PHP_EXTENSIONS }}

            - name: Install Composer packages
              run: composer update -q --no-ansi --no-interaction ${{ matrix.dependency_version }}

            - name: Run PHPUnit
              run: $GITHUB_WORKSPACE/vendor/bin/phpunit --coverage-text
